<a href="https://colab.research.google.com/github/marsrabin13/DI_Bootcamp/blob/colab/Week_6_Day_1_Numpy_Exercise_XP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

🌟 Exercise 1 : Array Creation and Manipulation
Instructions
Create a 1D NumPy array containing numbers from 0 to 9.

Expected Output:



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
import numpy as np
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


🌟 Exercise 2 : Type Conversion and Array Operations
Instructions
Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

Expected Output:



array([3, 2, 0, 1, 2])

In [ ]:
new_list = [3.14, 2.17, 0, 1, 2]
new_array = np.array(new_list, dtype=int)
print(new_array)

[3 2 0 1 2]


🌟 Exercise 3 : Working with Multi-Dimensional Arrays
Instructions
Create a 3x3 NumPy array with values ranging from 1 to 9.

Expected Output:



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array = np.arange(1,10)
new_array = array.reshape(3,3)
print(new_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers
Instructions
Create a 2D NumPy array of shape (4, 5) filled with random numbers.

Expected Output:



array([[0.56, 0.85, 0.01, 0.42, 0.68],
       [0.22, 0.37, 0.73, 0.93, 0.39],
       [0.44, 0.03, 0.87, 0.02, 0.83],
       [0.78, 0.87, 0.98, 0.80, 0.46]])

In [ ]:
import random
np.random.seed(42)
array = np.random.rand(4,5)
print(array)


[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]]


🌟 Exercise 5 : Indexing Arrays
Instructions
Select the second row from a given 2D NumPy array.

Expected Output:



array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])

In [ ]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
print(f"Second row: { array[1] }")

Second row: [20 21 22 23 24]


🌟 Exercise 6 : Reversing elements
Instructions
Reverse the order of elements in a given 1D NumPy array (first element becomes last).

Expected Output:



array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
arr = np.arange(10)
print(arr[::-1])

[9 8 7 6 5 4 3 2 1 0]


🌟 Exercise 7 : Identity Matrix
Instructions
Create a 4x4 identity matrix using NumPy.

Expected Output:



array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


🌟 Exercise 8 : Simple Aggregate Funcs
Instructions
Find the sum and average of a given 1D array.

Expected Output:



Sum: 45, Average: 4.5

In [ ]:
arr = np.array([15, 23, 8, 42, 16, 4, 37, 29, 11, 33])
print(f"Sum:  {arr.sum()}, Average {arr.mean()}")

Sum:  218, Average 21.8


🌟 Exercise 9 : Create Array and Change its Structure
Instructions
Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

Expected Output:



array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
new_array = np.arange(1,21).reshape(4,5)
print(new_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


🌟 Exercise 10 : Conditional Selection of Values
Instructions
Extract all odd numbers from a given NumPy array.

Expected Output:



array([1, 3, 5, 7, 9])


In [ ]:
arr = np.arange(10)
arr_odd = arr[arr % 2 ==1]
print(arr_odd)



[1 3 5 7 9]
